spring:
  datasource:
    # - [Features](http://www.h2database.com/html/features.html#in_memory_databases)
    url: jdbc:h2:mem:demo_test_db;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
    jpa:
      hibernate.ddl-auto: update
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Tokyo
# References
# - [H2 database example using hibernate and Spring Boot - My Cute Blog](http://mycuteblog.com/h2-database-example-hibernate-spring-boot/)
# - [Spring Boot お勉強　その３　～H2DBの永続化～ - yosshio0426's blog](http://yosshio0426.hatenadiary.com/entry/2014/07/21/070153)
# - [spring-boot-rest-example/application.yml at master · khoubyari/spring-boot-rest-example](https://github.com/khoubyari/spring-boot-rest-example/blob/master/src/main/resources
# - [Spring BootのJackson時刻設定まとめ - hogepiyoエンジニアリング](http://hogepiyo.hatenablog.jp/entry/2015/11/11/190252)
