spring:
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Tokyo
#Exposes Spring actuator endpoints
management:
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
    details:
      enabled: true
    application:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  metrics:
    export:
      datadog:
        enabled: false
# > Spring Actuatorが誰でもみれなくなっちゃったの巻 - BullよりElk
# > http://uchi-fashion.hatenablog.com/entry/2017/03/13/180000
#  security:
#    enabled: true

# > SpringBootActuatorを試してみる - Qiita
# > https://qiita.com/ozaki25/items/eb1d3615134cda4e620e
endpoints.prometheus.sensitive: false
