spring:
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Tokyo

#Exposes Spring actuator endpoints
management:
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        include: "*"


# > Spring Actuatorが誰でもみれなくなっちゃったの巻 - BullよりElk
# > http://uchi-fashion.hatenablog.com/entry/2017/03/13/180000
#  security:
#    enabled: true

