# > Spring Bootで起動／終了時のコンソール出力を抑制する - Qiita
# > https://qiita.com/tag1216/items/5c7271f5a90b7ab258b2
#
# > Spring Boot – How to disable the Spring logo banner – Mkyong.com
# > https://www.mkyong.com/spring-boot/spring-boot-how-to-disable-the-spring-logo-banner/
spring.main.show-banner: false
spring.main.log-startup-info: false
logging.level:
  org.springframework: WARN
